package config

var SHAYARI = []string{
    "🌺**बहुत अच्छा लगता है तुझे सताना और फिर प्यार से तुझे मनाना।**🌺 \n\n**🥀Bahut aacha lagta hai tujhe satana Aur fir pyar se tujhe manana.🥀**", 
    "🌺**मेरी जिंदगी मेरी जान हो तुम मेरे सुकून का दुसरा नाम हो तुम।**🌺 \n\n**🥀Meri zindagi Meri jaan ho tum Mere sukoon ka Dusra naam ho tum.🥀** ", 
    "🌺**तुम मेरी वो खुशी हो जिसके बिना, मेरी सारी खुशी अधूरी लगती है।**🌺 \n\n**🥀**Tum Meri Wo Khushi Ho Jiske Bina, Meri Saari Khushi Adhuri Lagti Ha.🥀** ", 
    "🌺**काश वो दिन जल्दी आए,जब तू मेरे साथ सात फेरो में बन्ध जाए।**🌺 \n\n**🥀Kash woh din jldi aaye Jb tu mere sath 7 feron me bndh jaye.🥀** ", 
    "🌺**अपना हाथ मेरे दिल पर रख दो और अपना दिल मेरे नाम कर दो।**🌺 \n\n**🥀apna hath mere dil pr rakh do aur apna dil mere naam kar do.🥀** ", 
    "🌺**महादेव ना कोई गाड़ी ना कोई बंगला चाहिए सलामत रहे मेरा प्यार बस यही दुआ चाहिए।**🌺 \n\n**🥀Mahadev na koi gadi na koi bangla chahiye salamat rhe mera pyar bas yahi dua chahiye.🥀** ", 
    "🌺**फिक्र तो होगी ना तुम्हारी इकलौती मोहब्बत हो तुम मेरी।**🌺 \n\n**🥀Fikr to hogi na tumhari ikloti mohabbat ho tum meri.🥀** ", 
    "🌺**सुनो जानू आप सिर्फ किचन संभाल लेना आप को संभालने के लिए मैं हूं ना।**🌺 \n\n**🥀suno jaanu aap sirf kitchen sambhal lena ap ko sambhlne ke liye me hun naa.🥀** ", 
    "🌺**सौ बात की एक बात मुझे चाहिए बस तेरा साथ।**🌺 \n\n**🥀So bat ki ek bat mujhe chahiye bas tera sath.🥀** ", 
    "🌺**बहुत मुश्किलों से पाया हैं तुम्हें, अब खोना नहीं चाहते,कि तुम्हारे थे तुम्हारे हैं अब किसी और के होना नहीं चाहते।**🌺 \n\n**🥀Bahut muskilon se paya hai tumhe Ab khona ni chahte ki tumhare they tumhare hai ab kisi or k hona nhi chahte.🥀** ", 
    "🌺**बेबी बातें तो रोज करते है चलो आज रोमांस करते है।**🌺 \n\n**🥀Baby baten to roj karte haichalo aaj romance karte hai..🥀** ", 
    "🌺**सुबह शाम तुझे याद करते है हम और क्या बताएं की तुमसे कितना प्यार करते है हम।**🌺 \n\n**🥀subha sham tujhe yad karte hai hum aur kya batayen ki tumse kitna pyar karte hai hum.🥀** ", 
    "🌺**किसी से दिल लग जाने को मोहब्बत नहीं कहते जिसके बिना दिल न लगे उसे मोहब्बत कहते हैं।**🌺 \n\n**🥀Kisi se dil lag jane ko mohabbat nahi kehte jiske nina dil na lage use mohabbat kehte hai.🥀** ", 
    " 🌺**मेरे दिल के लॉक की चाबी हो तुम क्या बताएं जान मेरे जीने की एकलौती वजह हो तुम।**🌺 \n\n**🥀mere dil ke lock ki chabi ho tum kya batayen jaan mere jeene ki eklauti wajah ho tum..🥀** ", 
    " 🌺**हम आपकी हर चीज़ से प्यार कर लेंगे, आपकी हर बात पर ऐतबार कर लेंगे, बस एक बार कह दो कि तुम सिर्फ मेरे हो, हम ज़िन्दगी भर आपका इंतज़ार कर लेंगे।**🌺 \n\n**🥀Hum apki har cheez se pyar kar lenge apki har baat par etvar kar lenge bas ek bar keh do ki tum sirf mere ho hum zindagi bhar apka intzaar kar lenge..🥀** ", 
    " 🌺**मोहब्बत कभी स्पेशल लोगो से नहीं होती जिससे होती है वही स्पेशल बन जाता है।**🌺 \n\n**🥀Mohabbat kabhi special logo se nahi hoti jisse bhi hoti hai wahi special ban jate hai,.🥀**", 
    " 🌺**तू मेरी जान है इसमें कोई शक नहीं तेरे अलावा मुझ पर किसी और का हक़ नहीं।**🌺 \n\n**🥀Tu meri jaan hai isme koi shak nahi tere alawa mujhe par kisi aur ka hak nhi..🥀** ", 
    " 🌺**पहली मोहब्बत मेरी हम जान न सके, प्यार क्या होता है हम पहचान न सके, हमने उन्हें दिल में बसा लिया इस कदर कि, जब चाहा उन्हें दिल से निकाल न सके।**🌺 \n\n**🥀Pehli mohabbat meri hum jaan na sake pyar kya hota hai hum pehchan na sake humne unhe dil me basa liya is kadar ki jab chaha unhe dil se nikal na sake.🥀** ", 
    " 🌺**खुद नहीं जानती वो कितनी प्यारी हैं , जान है हमारी पर जान से प्यारी हैं, दूरियों के होने से कोई फर्क नहीं पड़ता वो कल भी हमारी थी और आज भी हमारी है.**🌺 \n\n**🥀khud nahi janti vo kitni pyari hai jan hai hamari par jan se jyda payari hai duriya ke hone se frak nahi pdta vo kal bhe hamari the or aaj bhe hamari hai.🥀** ", 
    " 🌺**चुपके से आकर इस दिल में उतर जाते हो, सांसों में मेरी खुशबु बनके बिखर जाते हो, कुछ यूँ चला है तेरे इश्क का जादू, सोते-जागते तुम ही तुम नज़र आते हो।**🌺 \n\n**🥀Chupke Se Aakar Iss Dil Mein Utar Jate Ho, Saanso Mein Meri Khushbu BanKe Bikhar Jate Ho,Kuchh Yun Chala Hai Tere Ishq Ka Jadoo, Sote-Jagte Tum Hi Tum Najar Aate Ho..🥀** ", 
    " 🌺**प्यार करना सिखा है नफरतो का कोई ठौर नही, बस तु ही तु है इस दिल मे दूसरा कोई और नही.**🌺 \n\n**🥀Pyar karna sikha hai naftaro ka koi thor nahi bas tu hi tu hai is dil me dusra koi aur nahi hai.🥀** ", 
    " 🌺**रब से आपकी खुशीयां मांगते है, दुआओं में आपकी हंसी मांगते है, सोचते है आपसे क्या मांगे,चलो आपसे उम्र भर की मोहब्बत मांगते है।**🌺\n\n**🥀Rab se apki khushiyan mangte hai duao me apki hansi mangte hai sochte hai apse kya mange chalo apse umar bhar ki mohabbat mangte hai..🥀** ", 
    " 🌺**काश मेरे होंठ तेरे होंठों को छू जाए देखूं जहा बस तेरा ही चेहरा नज़र आए हो जाए हमारा रिश्ता कुछ ऐसा होंठों के साथ हमारे दिल भी जुड़ जाए.**🌺\n\n**🥀kash mere hoth tere hontho ko chu jayen dekhun jaha bas teri hi chehra nazar aaye ho jayen humara rishta kuch easa hothon ke sath humare dil bhi jud jaye.🥀** ", 
    " 🌺**आज मुझे ये बताने की इजाज़त दे दो, आज मुझे ये शाम सजाने की इजाज़त दे दो, अपने इश्क़ मे मुझे क़ैद कर लो,आज जान तुम पर लूटाने की इजाज़त दे दो.**🌺\n\n**🥀Aaj mujhe ye batane ki izazat de do, aaj mujhe ye sham sajane ki izazat de do, apne ishq me mujhe ked kr lo aaj jaan tum par lutane ki izazat de do..🥀** ", 
    " 🌺**जाने लोग मोहब्बत को क्या क्या नाम देते है, हम तो तेरे नाम को ही मोहब्बत कहते है.**🌺\n\n**🥀Jane log mohabbat ko kya kya naam dete hai hum to tere naam ko hi mohabbat kehte hai..🥀** ", 
    " 🌺**देख के हमें वो सिर झुकाते हैं। बुला के महफिल में नजर चुराते हैं। नफरत हैं हमसे तो भी कोई बात नहीं। पर गैरो से मिल के दिल क्यों जलाते हो।**🌺\n\n**🥀Dekh Ke Hame Wo Sir Jhukate Hai Bula Ke Mahfhil Me Najar Churate Hai Nafrat Hai Hamse To Bhi Koei Bat Nhi Par Gairo Se Mil Ke Dil Kyo Jalate Ho.🥀** ", 
    " 🌺**तेरे बिना टूट कर बिखर जायेंगे,तुम मिल गए तो गुलशन की तरह खिल जायेंगे, तुम ना मिले तो जीते जी ही मर जायेंगे, तुम्हें जो पा लिया तो मर कर भी जी जायेंगे।**🌺\n\n**🥀Tere bina tut kar bikhar jeynge tum mil gaye to gulshan ki tarha khil jayenge tum na mile to jite ji hi mar jayenge tumhe jo pa liya to mar kar bhi ji jayenge..🥀** ", 
    " 🌺**सनम तेरी कसम जेसे मै जरूरी हूँ तेरी ख़ुशी के लिये, तू जरूरी है मेरी जिंदगी के लिये.**🌺\n\n**🥀Sanam teri kasam jese me zaruri hun teri khushi ke liye tu zaruri hai meri zindagi ke liye.🥀** ", 
    " 🌺**तुम्हारे गुस्से पर मुझे बड़ा प्यार आया हैं इस बेदर्द दुनिया में कोई तो हैं जिसने मुझे पुरे हक्क से धमकाया हैं.**🌺\n\n**🥀Tumharfe gusse par mujhe pyar aaya hai is bedard duniya me koi to hai jisne mujhe pure hakk se dhamkaya hai.🥀** ", 
    " 🌺**पलको से आँखो की हिफाजत होती है धडकन दिल की अमानत होती है ये रिश्ता भी बडा प्यारा होता है कभी चाहत तो कभी शिकायत होती है.**🌺\n\n**🥀Palkon se Aankho ki hifajat hoti hai dhakad dil ki Aamanat hoti hai, ye rishta bhi bada pyara hota hai, kabhi chahat to kabhi shikayat hoti hai.🥀** ", 
    " 🌺**मुहब्बत को जब लोग खुदा मानते हैं प्यार करने वाले को क्यों बुरा मानते हैं। जब जमाना ही पत्थर दिल हैं। फिर पत्थर से लोग क्यों दुआ मांगते है।**🌺\n\n**🥀Muhabbt Ko Hab Log Khuda Mante Hai, Payar Karne Walo Ko Kyu Bura Mante Hai,Jab Jamana Hi Patthr Dil Hai,Fhir Patthr Se Log Kyu Duaa Magte Hai.🥀** ", 
    " 🌺**हुआ जब इश्क़ का एहसास उन्हें आकर वो पास हमारे सारा दिन रोते रहे हम भी निकले खुदगर्ज़ इतने यारो कि ओढ़ कर कफ़न, आँखें बंद करके सोते रहे।**🌺\n\n**🥀Hua jab ishq ka ehsaas unhe akar wo pass humare sara din rate rahe, hum bhi nikale khudgarj itne yaro ki ood kar kafan ankhe band krke sote rhe.🥀** ", 
    " 🌺**दिल के कोने से एक आवाज़ आती हैं। हमें हर पल उनकी याद आती हैं। दिल पुछता हैं बार -बार हमसे के जितना हम याद करते हैं उन्हें क्या उन्हें भी हमारी याद आती हैं।**🌺\n\n**🥀Dil Ke Kone Se Ek Aawaj Aati Hai, Hame Har Pal Uaski Yad Aati Hai, Dil Puchhta Hai Bar Bar Hamse Ke, Jitna Ham Yad Karte Hai Uanhe, Kya Uanhe Bhi Hamari Yad Aati Hai,🥀** ", 
    " 🌺**कभी लफ्ज़ भूल जाऊं कभी बात भूल जाऊं, तूझे इस कदर चाहूँ कि अपनी जात भूल जाऊं, कभी उठ के तेरे पास से जो मैं चल दूँ, जाते हुए खुद को तेरे पास भूल जाऊं।**🌺\n\n**🥀Kabhi Lafz Bhool Jaaun Kabhi Baat Bhool Jaaun, Tujhe Iss Kadar Chahun Ki Apni Jaat Bhool Jaaun, Kabhi Uthh Ke Tere Paas Se Jo Main Chal Dun, Jaate Huye Khud Ko Tere Paas Bhool Jaaun..🥀** ", 
    " 🌺**आईना देखोगे तो मेरी याद आएगी साथ गुज़री वो मुलाकात याद आएगी पल भर क लिए वक़्त ठहर जाएगा, जब आपको मेरी कोई बात याद आएगी.**🌺\n\n**🥀Aaina dekhoge to meri yad ayegi sath guzari wo mulakat yad ayegi pal bhar ke waqt thahar jayega jab apko meri koi bat yad ayegi.🥀** ", 
    " 🌺**प्यार किया तो उनकी मोहब्बत नज़र आई दर्द हुआ तो पलके उनकी भर आई दो दिलों की धड़कन में एक बात नज़र आई दिल तो उनका धड़का पर आवाज़ इस दिल की आई.**🌺\n\n**🥀Pyar kiya to unki mohabbat nazar aai dard hua to palke unki bhar aai do dilon ki dhadkan me ek baat nazar aai dil to unka dhadka par awaz dil ki aai.🥀** ", 
    " 🌺**कई चेहरे लेकर लोग यहाँ जिया करते हैं हम तो बस एक ही चेहरे से प्यार करते हैं ना छुपाया करो तुम इस चेहरे को,क्योंकि हम इसे देख के ही जिया करते हैं.**🌺\n\n**🥀Kai chehre lekar log yahn jiya karte hai hum to bas ek hi chehre se pyar karte hai na chupaya karo tum is chehre ko kyuki hum ise dekh ke hi jiya karte hai.🥀** ", 
    " 🌺**सबके bf को अपनी gf से बात करके नींद आजाती है और मेरे वाले को मुझसे लड़े बिना नींद नहीं आती।**🌺\n\n**🥀Sabke bf ko apni gf se baat karke nind aajati hai aur mere wale ko mujhse lade bina nind nhi aati.🥀** ", 
    " 🌺**सच्चा प्यार कहा किसी के नसीब में होता है. एसा प्यार कहा इस दुनिया में किसी को नसीब होता है.**🌺\n\n**🥀Sacha pyar kaha kisi ke nasib me hota hai esa pyar kahan is duniya me kisi ko nasib hota hai.🥀** ",
}

var RAID = []string{
    "MADARCHOD TERI MAA KI CHUT ME GHUTKA KHAAKE THOOK DUNGA 🤣🤣",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
    "TERI VAHEEN NHI HAI KYA? 9 MAHINE RUK SAGI VAHEEN DETA HU 🤣🤣🤩",
    "TERI MAA K BHOSDE ME AEROPLANEPARK KARKE UDAAN BHAR DUGA ✈️🛫",
    "TERI MAA KI CHUT ME SUTLI BOMB FOD DUNGA TERI MAA KI JHAATE JAL KE KHAAK HO JAYEGI💣",
    "TERI MAAKI CHUT ME SCOOTER DAAL DUGA👅",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
    "TERI MAA KI CHUT KAKTE 🤱 GALI KE KUTTO 🦮 ME BAAT DUNGA PHIR 🍞 BREAD KI TARH KHAYENGE WO TERI MAA KI CHUT",
    "DUDH HILAAUNGA TERI VAHEEN KE UPR NICHE 🆙🆒😙",
    "TERI MAA KI CHUT ME ✋ HATTH DALKE 👶 BACCHE NIKAL DUNGA 😍",
    "TERI BEHN KI CHUT ME KELE KE CHILKE 🍌🍌😍",
    "TERI BHEN KI CHUT ME USERBOT LAGAAUNGA SASTE SPAM KE CHODE",
    "TERI VAHEEN DHANDHE VAALI 😋😛",
    "TERI MAA KE BHOSDE ME AC LAGA DUNGA SAARI GARMI NIKAL JAAYEGI",
    "TERI VAHEEN KO HORLICKS PEELAUNGA MADARCHOD😚",
    "TERI MAA KI GAAND ME SARIYA DAAL DUNGA MADARCHOD USI SARIYE PR TANG KE BACHE PAIDA HONGE 😱😱",
    "TERI MAA KO KOLKATA VAALE JITU BHAIYA KA LUND MUBARAK 🤩🤩",
    "TERI MUMMY KI FANTASY HU LAWDE, TU APNI BHEN KO SMBHAAL 😈😈",
    "TERA PEHLA BAAP HU MADARCHOD ",
    "TERI VAHEEN KE BHOSDE ME XVIDEOS.COM CHALA KE MUTH MAARUNGA 🤡😹",
    "TERI MAA KA GROUP VAALON SAATH MILKE GANG BANG KRUNGA🙌🏻☠️ ",
    "TERI ITEM KI GAAND ME LUND DAALKE,TERE JAISA EK OR NIKAAL DUNGA MADARCHOD🤘🏻🙌🏻☠️ ",
    "AUKAAT ME REH VRNA GAAND ME DANDA DAAL KE MUH SE NIKAAL DUNGA SHARIR BHI DANDE JESA DIKHEGA 🙄🤭🤭",
    "TERI MUMMY KE SAATH LUDO KHELTE KHELTE USKE MUH ME APNA LODA DE DUNGA☝🏻☝🏻😬",
    "TERI VAHEEN KO APNE LUND PR ITNA JHULAAUNGA KI JHULTE JHULTE HI BACHA PAIDA KR DEGI👀👯 ",
    "TERI MAA KI CHUT MEI BATTERY LAGA KE POWERBANK BANA DUNGA 🔋 🔥🤩",
    "TERI MAA KI CHUT MEI C++ STRING ENCRYPTION LAGA DUNGA BAHTI HUYI CHUT RUK JAYEGIIII😈🔥😍",
    "TERI MAA KE GAAND MEI JHAADU DAL KE MOR 🦚 BANA DUNGAA 🤩🥵😱",
    "TERI CHUT KI CHUT MEI SHOULDERING KAR DUNGAA HILATE HUYE BHI DARD HOGAAA😱🤮👺",
    "TERI MAA KO REDI PE BAITHAL KE USSE USKI CHUT BILWAUNGAA 💰 😵🤩",
    "BHOSDIKE TERI MAA KI CHUT MEI 4 HOLE HAI UNME MSEAL LAGA BAHUT BAHETI HAI BHOFDIKE👊🤮🤢🤢",
    "TERI BAHEN KI CHUT MEI BARGAD KA PED UGA DUNGAA CORONA MEI SAB OXYGEN LEKAR JAYENGE🤢🤩🥳",
    "TERI MAA KI CHUT MEI SUDO LAGA KE BIGSPAM LAGA KE 9999 FUCK LAGAA DU 🤩🥳🔥",
    "TERI VAHEN KE BHOSDIKE MEI BESAN KE LADDU BHAR DUNGA🤩🥳🔥😈",
    "TERI MAA KI CHUT KHOD KE USME CYLINDER ⛽️ FIT KARKE USMEE DAL MAKHANI BANAUNGAAA🤩👊🔥",
    "TERI MAA KI CHUT MEI SHEESHA DAL DUNGAAA AUR CHAURAHE PE TAANG DUNGA BHOSDIKE😈😱🤩",
    "TERI MAA KI CHUT MEI CREDIT CARD DAL KE AGE SE 500 KE KAARE KAARE NOTE NIKALUNGAA BHOSDIKE💰💰🤩",
    "TERI MAA KE SATH SUAR KA SEX KARWA DUNGAA EK SATH 6-6 BACHE DEGI💰🔥😱",
    "TERI BAHEN KI CHUT MEI APPLE KA 18W WALA CHARGER 🔥🤩",
    "TERI BAHEN KI GAAND MEI ONEPLUS KA WRAP CHARGER 30W HIGH POWER 💥😂😎",
    "TERI BAHEN KI CHUT KO AMAZON SE ORDER KARUNGA 10 rs MEI AUR FLIPKART PE 20 RS MEI BECH DUNGA🤮👿😈🤖",
    "TERI MAA KI BADI BHUND ME ZOMATO DAL KE SUBWAY KA BFF VEG SUB COMBO [15cm , 16 inches ] ORDER COD KRVAUNGA OR TERI MAA JAB DILIVERY DENE AYEGI TAB USPE JAADU KRUNGA OR FIR 9 MONTH BAAD VO EK OR FREE DILIVERY DEGI🙀👍🥳🔥",
    "TERI BHEN KI CHUT KAALI🙁🤣💥",
    "TERI MAA KI CHUT ME CHANGES COMMIT KRUGA FIR TERI BHEEN KI CHUT AUTOMATICALLY UPDATE HOJAAYEGI🤖🙏🤔",
    "TERI MAUSI KE BHOSDE MEI INDIAN RAILWAY 🚂💥😂",
    "TU TERI BAHEN TERA KHANDAN SAB BAHEN KE LAWDE RANDI HAI RANDI 🤢✅🔥",
    "TERI BAHEN KI CHUT MEI IONIC BOND BANA KE VIRGINITY LOOSE KARWA DUNGA USKI 📚 😎🤩",
    "TERI RANDI MAA SE PUCHNA BAAP KA NAAM BAHEN KE LODEEEEE 🤩🥳😳",
    "TU AUR TERI MAA DONO KI BHOSDE MEI METRO CHALWA DUNGA MADARXHOD 🚇🤩😱🥶",
    "TERI MAA KO ITNA CHODUNGA TERA BAAP BHI USKO PAHCHANANE SE MANA KAR DEGA😂👿🤩",
    "TERI BAHEN KE BHOSDE MEI HAIR DRYER CHALA DUNGAA💥🔥🔥",
    "TERI MAA KI CHUT MEI TELEGRAM KI SARI RANDIYON KA RANDI KHANA KHOL DUNGAA👿🤮😎",
    "TERI MAA KI CHUT ALEXA DAL KEE DJ BAJAUNGAAA 🎶 ⬆️🤩💥",
    "TERI MAA KE BHOSDE MEI GITHUB DAL KE APNA BOT HOST KARUNGAA 🤩👊👤😍",
    "TERI BAHEN KA VPS BANA KE 24*7 BASH CHUDAI COMMAND DE DUNGAA 🤩💥🔥🔥",
    "TERI MUMMY KI CHUT MEI TERE LAND KO DAL KE KAAT DUNGA MADARCHOD 🔪😂🔥",
    "SUN TERI MAA KA BHOSDA AUR TERI BAHEN KA BHI BHOSDA 👿😎👊",
    "TUJHE DEKH KE TERI RANDI BAHEN PE TARAS ATA HAI MUJHE BAHEN KE LODEEEE 👿💥🤩🔥",
    "SUN MADARCHOD JYADA NA UCHAL MAA CHOD DENGE EK MIN MEI ✅🤣🔥🤩",
    "APNI AMMA SE PUCHNA USKO US KAALI RAAT MEI KAUN CHODNEE AYA THAAA! TERE IS PAPA KA NAAM LEGI 😂👿😳",
    "TOHAR BAHIN CHODU BBAHEN KE LAWDE USME MITTI DAL KE CEMENT SE BHAR DU 🏠🤢🤩💥",
    "TUJHE AB TAK NAHI SMJH AYA KI MAI HI HU TUJHE PAIDA KARNE WALA BHOSDIKEE APNI MAA SE PUCH RANDI KE BACHEEEE 🤩👊👤😍",
    "TERI MAA KE BHOSDE MEI SPOTIFY DAL KE LOFI BAJAUNGA DIN BHAR 😍🎶🎶💥",
    "TERI MAA KA NAYA RANDI KHANA KHOLUNGA CHINTA MAT KAR 👊🤣🤣😳",
    "TERA BAAP HU BHOSDIKE TERI MAA KO RANDI KHANE PE CHUDWA KE US PAISE KI DAARU PEETA HU 🍷🤩🔥",
    "TERI BAHEN KI CHUT MEI APNA BADA SA LODA GHUSSA DUNGAA KALLAAP KE MAR JAYEGI 🤩😳😳🔥",
    "TOHAR MUMMY KI CHUT MEI PURI KI PURI KINGFISHER KI BOTTLE DAL KE TOD DUNGA ANDER HI 😱😂🤩",
    "TERI MAA KO ITNA CHODUNGA KI SAPNE MEI BHI MERI CHUDAI YAAD KAREGI RANDI 🥳😍👊💥",
    "TERI MUMMY AUR BAHEN KO DAUDA DAUDA NE CHODUNGA UNKE NO BOLNE PE BHI LAND GHUSA DUNGA ANDER TAK 😎😎🤣🔥",
    "TERI MUMMY KI CHUT KO ONLINE OLX PE BECHUNGA AUR PAISE SE TERI BAHEN KA KOTHA KHOL DUNGA 😎🤩😝😍",
    "TERI MAA KE BHOSDA ITNA CHODUNGA KI TU CAH KE BHI WO MAST CHUDAI SE DUR NHI JA PAYEGAA 😏😏🤩😍",
    "SUN BE RANDI KI AULAAD TU APNI BAHEN SE SEEKH KUCH KAISE GAAND MARWATE HAI😏🤬🔥💥",
    "TERI MAA KA YAAR HU MEI AUR TERI BAHEN KA PYAAR HU MEI AJA MERA LAND CHOOS LE 🤩🤣💥",
    "TERI BHEN KI CHUT ME USERBOT LAGAAUNGA SASTE SPAM KE CHODE",
    "TERI MAA KI GAAND ME SARIYA DAAL DUNGA MADARCHOD USI SARIYE PR TANG KE BACHE PAIDA HONGE 😱😱",
    "TERI MAA KI CHUT ME ✋ HATTH DALKE 👶 BACCHE NIKAL DUNGA 😍",
    "TERI BEHN KI CHUT ME KELE KE CHILKE 🤤🤤",
    "TERI MAA KI CHUT ME SUTLI BOMB FOD DUNGA TERI MAA KI JHAATE JAL KE KHAAK HO JAYEGI💣💋",
    "TERI VAHEEN KO HORLICKS PEELAKE CHODUNGA MADARCHOD😚",
    "TERI ITEM KI GAAND ME LUND DAALKE,TERE JAISA EK OR NIKAAL DUNGA MADARCHOD😆🤤💋",
    "TERI VAHEEN KO APNE LUND PR ITNA JHULAAUNGA KI JHULTE JHULTE HI BACHA PAIDA KR DEGI 💦💋",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "MADARCHOD",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulda",
    "Kutte ka awlat",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP",
}


var PUNRAID = []string{
	"ਮਾਦਰਚੋਦ ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਘੁਟਕਾ ਖਾ ਕੇ ਥੂਕ ਦੂੰਗਾ 🤣🤣",
	"ਮਾਦਰਚੋਦ ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਛੁਰਾ ਮਾਰ ਕੇ ਖੂਨ ਕੱਢ ਦੂੰਗਾ 🥵",
	"ਤੇਰੀ ਭੈਣ ਦੀ ਚੁੱਤ ਵਿਚ ਚਾਕੂ ਡਾਲ ਕੇ ਫਾੜ ਦੂੰਗਾ 😈",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਐਰੋਪਲੇਨ ਪਾਰਕ ਕਰਕੇ ਉਡਾਨ ਭਰ ਦੂੰਗਾ ✈️🛫",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਸੁਤਲੀ ਬੰਬ ਫੋਡ ਦੂੰਗਾ ਝਾਟੇ ਜਲ ਕੇ ਖਾਕ ਹੋ ਜਾਣਗੇ 💣",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਸਕੂਟਰ ਡਾਲ ਦੂੰਗਾ 👅",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਗਲੀ ਦੇ ਕੁੱਤਿਆਂ ਵਿਚ ਬਾਟ ਦੂੰਗਾ ਫਿਰ ਬ੍ਰੈਡ ਵਾਂਗ ਖਾਣਗੇ 🦮🍞",
	"ਦੁੱਧ ਹਿਲਾਉਂਗਾ ਤੇਰੀ ਭੈਣ ਦੀਆਂ ਉਪਰ-ਹੇਠਾਂ 🆙😙",
	"ਤੇਰੀ ਭੈਣ ਦੀ ਚੁੱਤ ਵਿਚ ਮੇਰਾ ਲੁੱਲ ਡਾਲ ਕੇ ਗਰਭਵਤੀ ਕਰ ਦੂੰਗਾ 🍌😍",
	"ਤੇਰੀ ਵਹੀਨ ਧੰਦੇ ਵਾਲੀ ਰਾਂਡ 😋😛",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਏਸੀ ਲਗਾ ਦੂੰਗਾ ਸਾਰੀ ਗਰਮੀ ਨਿਕਲ ਜਾਵੇਗੀ ❄️",
	"ਤੇਰੀ ਵਹੀਨ ਨੂੰ ਹਾਰਲਿਕਸ ਪਿਲਾਉਂਗਾ ਮਾਦਰਚੋਦ 😚",
	"ਤੇਰੀ ਮਾਂ ਨੂੰ ਕੋਲਕਾਤਾ ਵਾਲਾ ਜੀਤੂ ਭਾਈਆ ਦਾ ਲੁੱਲ ਮੁਬਾਰਕ 🤩",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਫੈਂਟਸੀ ਹਾਂ ਲਾਵਡੇ, ਤੂੰ ਆਪਣੀ ਭੈਣ ਸੰਭਾਲ 😈",
	"ਤੇਰਾ ਪਹਿਲਾ ਬਾਪ ਹਾਂ ਮਾਦਰਚੋਦ",
	"ਤੇਰੀ ਵਹੀਨ ਦੀ ਚੁੱਤ ਵਿਚ xvideos.com ਚਲਾ ਕੇ ਮੁੱਠ ਮਾਰੂੰਗਾ 🤡😹",
	"ਤੇਰੀ ਮਾਂ ਦਾ ਗਰੁੱਪ ਵਾਲਿਆਂ ਨਾਲ ਮਿਲ ਕੇ ਗੈਂਗਬੈਂਗ ਕਰੂੰਗਾ 🙌🏻☠️",
	"ਤੇਰੀ ਆਈਟਮ ਦੀ ਗਾਂਡ ਵਿਚ ਲੁੱਲ ਡਾਲ ਕੇ ਤੇਰੇ ਵਰਗਾ ਇੱਕ ਹੋਰ ਨਿਕਾਲ ਦੂੰਗਾ 😆",
	"ਔਕਾਤ ਵਿਚ ਰਹਿ ਵਰਨਾ ਗਾਂਡ ਵਿਚ ਡੰਡਾ ਡਾਲ ਕੇ ਮੂੰਹ ਤੋਂ ਨਿਕਾਲ ਦੂੰਗਾ 🙄🤭",
	"ਤੇਰੀ ਮਮੀ ਨਾਲ ਲੂਡੋ ਖੇਡਦੇ ਖੇਡਦੇ ਉਸ ਦੇ ਮੂੰਹ ਵਿਚ ਆਪਣਾ ਲੋਡਾ ਦੇ ਦੂੰਗਾ ☝🏻😬",
	"ਤੇਰੀ ਵਹੀਨ ਨੂੰ ਆਪਣੇ ਲੁੱਲ ਉੱਪਰ ਇੰਨਾ ਝੁਲਾਉਂਗਾ ਕਿ ਝੁਲਦੀ ਝੁਲਦੀ ਬੱਚਾ ਪੈਦਾ ਕਰ ਦੇਗੀ 💦",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਬੈਟਰੀ ਲਗਾ ਕੇ ਪਾਵਰਬੈਂਕ ਬਣਾ ਦੂੰਗਾ 🔋🔥",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ C++ ਸਟ੍ਰਿੰਗ ਐਨਕ੍ਰਿਪਸ਼ਨ ਲਗਾ ਦੂੰਗਾ ਬਹੁਤ ਬਹਿਤੀ ਚੁੱਤ ਰੁੱਕ ਜਾਵੇਗੀ 😈",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਗਾਂਡ ਵਿਚ ਝਾੜੂ ਡਾਲ ਕੇ ਮੋਰ ਬਣਾ ਦੂੰਗਾ 🦚",
	"ਤੇਰੀ ਚੁੱਤ ਦੀ ਚੁੱਤ ਵਿਚ ਸ਼ੋਲਡਰਿੰਗ ਕਰ ਦੂੰਗਾ ਹਿਲਾਉਂਦੇ ਹੋਏ ਵੀ ਦਰਦ ਹੋਵੇਗਾ 😱",
	"ਤੇਰੀ ਮਾਂ ਨੂੰ ਰੇਡੀ ਉੱਪਰ ਬਿਠਾ ਕੇ ਉਸ ਦੀ ਚੁੱਤ ਬਿਲਵਾਉਂਗਾ 💰😵",
	"ਭੋਸੜੀਕੇ ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ 4 ਛੇਕ ਹਨ ਉਹਨਾਂ ਵਿਚ ਮਸਾਲ ਲਗਾ ਬਹੁਤ ਬਹਿਤੀ ਹੈ 👊🤮",
	"ਤੇਰੀ ਭੈਣ ਦੀ ਚੁੱਤ ਵਿਚ ਬਰਗਦ ਦਾ ਪੇੜ ਉਗਾ ਦੂੰਗਾ ਕੋਰੋਨਾ ਵਿਚ ਆਕਸੀਜਨ ਲੈ ਕੇ ਜਾਣਗੇ 🤢🤩",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਸੁਡੋ ਲਗਾ ਕੇ ਬਿਗ ਸਪੈਮ ਲਗਾ ਕੇ 9999 ਫੱਕ ਲਗਾ ਦੂੰਗਾ 🤩🔥",
	"ਤੇਰੀ ਵਹੀਨ ਦੀ ਭੋਸੜੀ ਵਿਚ ਬੇਸਨ ਦੇ ਲੱਡੂ ਭਰ ਦੂੰਗਾ 🤩🥳",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਖੋਦ ਕੇ ਉਸ ਵਿਚ ਸਿਲੰਡਰ ਫਿੱਟ ਕਰਕੇ ਦਾਲ ਮੱਖਣੀ ਬਣਾਉਂਗਾ 🤩👊",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਸ਼ੀਸ਼ਾ ਡਾਲ ਦੂੰਗਾ ਚੌਰਾਹੇ ਉੱਪਰ ਟੰਗ ਦੂੰਗਾ ਭੋਸੜੀਕੇ 😈😱",
	"ਤੇਰੀ ਮਾਂ ਦੀ ਚੁੱਤ ਵਿਚ ਕ੍ਰੈਡਿਟ ਕਾਰਡ ਡਾਲ ਕੇ 500 ਦੇ ਕਾਲੇ ਨੋਟ ਨਿਕਾਲੂਂਗਾ 💰🤩",
	"ਤੇਰੀ ਮਾਂ ਦੇ ਨਾਲ ਸੂਅਰ ਦਾ ਸੈਕਸ ਕਰਵਾ ਦੂੰਗਾ ਇੱਕ ਵਾਰੀ 6-6 ਬੱਚੇ ਦੇਵੇਗੀ 💰🔥😱",
	"ਤੇਰੀ ਭੈਣ ਦੀ ਚੁੱਤ ਵਿਚ ਐਪਲ ਦਾ 18W ਚਾਰਜਰ 🔥🤩",
	"ਤੇਰੀ ਭੈਣ ਦੀ ਗਾਂਡ ਵਿਚ ਓਨਪਲੱਸ ਦਾ 30W ਵ੍ਰੈਪ ਚਾਰਜਰ 💥😂😎",
}



var HRAID = []string{
    "मादरचोद तेरी माँ की चूत में घुटका खाके थूक दूंगा 🤣🤣", 
    "मादरचोद तेरी माँ की चूत में घुटका खाके थूक दूंगा 🤣🤣", 
    "तेरे बहन की चूत में चाकू डाल कर चूत का खून कर दूँगा", 
    "तेरी माँ की चूत में शैतान का लौड़ा 🤣🤣",
    "तेरी वहीं नहीं है क्या? 9 महीने रुक सगी वहीं देता हूं 🤣🤣🤩",
    "तेरी मां के भोसड़े में एयरोप्लेनपार्क करके उड़ान भर दूंगा ✈️🛫",
    "तेरी मां की चूत में सुतली बम फोड़ दूंगा तेरी माँ की झाटे जल के खाक हो जाएगी💣",
    "तेरी माँ की चूत में स्कूटर डाल दूँगा👅","तेरी माँ की चूत में शैतान का लौड़ा 🤣🤣",
    "तेरे बहन की चूत में चाकू डाल कर चूत का खून कर दुगा",
    "तेरे बहन की चूत में चाकू डाल कर चूत का खून कर दूंगा",
    "तेरी माँ की चूत 🤱गली के कुट्टो 🦮मैं बात दूँगा फिर 🍞ब्रेड की तरह खाएँगे वो तेरी माँ की चूत",
    "दूध हिलाऊंगा तेरी दीवारों के ऊपर नीचे 🆙🆒😙",
    "तेरी मां की चूत में ✋ हत्थ डालके 👶 बच्चे निकाल दूंगा 😍",
    "तेरी बहन की चूत में काले के छिलके 🍌🍌😍",
    "तेरी बहन की चूत में यूजरबोट लू अगाउंगा सस्ते स्पैम के छोड़े",
    "तेरी वहीं धंधे वाली 😋😛",
    "तेरी मां के भोसड़े में एसी लगा दूंगा सारी गर्मी निकल जाएगी",
    "तेरी कारों को हॉर्लिक्स पिलाऊंगा मादरचोद😚",
    "तेरी मां की चूत में शैतान का लौड़ा 🤣🤣 ",
    "तेरी मां की गांड में सरिया डाल दूंगा मादरचोद उसी साड़ी में पीआर टांग के बच्चे पैदा होंगे 😱😱",
    "तेरी मां को कोलकाता वाले जीतू भैया का लंड मुबारक 🤩🤩","तेरी मां की फैंटेसी हूं बेटे, तू अपनी बहन को संभाल 😈😈",
    "तेरा पहला बाप हूं मादरचोद","तेरी वही के भोसड़े में XVIDEOS.COM चला के मुंह मारूंगा 🤡😹",
    "तेरी मां का ग्रुप वालों साथ मिलके गैंग बैंग करूंगा🙌🏻☠️",
    "तेरी आइटम कि गांड में लंड डालके, तेरे जैसा एक या निकाल दूंगा मादरचोद🤘🏻🙌🏻☠️ ",
    "औकात में रह वरना गांड में डंडा डाल के मुंह से निकाल दूंगा शरीर भी डंडे जैसा दिखेगा 🙄🤭🤭",
    "तेरी मां मेरे साथ लूडो खेलते-खेलते उसके मुंह में अपना लोडा दे दूंगा☝🏻☝🏻😬",
    "तेरी योनि को अपने लंड पर इतना झूलाउंगा कि झूलते-झूलते ही बच्चा पैदा कर देगी👀👯",
    "तेरी मां की चूत में बैटरी लगा के पावरबैंक बना डी यूएनजीए 🔋 🔥🤩",
    "तेरी मां की चूत में सी स्ट्रिंग एन्क्रिप्शन लगा दूंगा बहुत हुई छुट रुक जाएगीIII😈🔥😍",
    "तेरी मां के गांड में झाड़ू दाल के मोर 🦚बना दूंगा 🤩🥵😱",
    "तेरी मां के गांड में झाड़ू डाल के मोर 🦚बना दूंगा 🤩🥵😱",
    "तेरी मां के गांड में झाड़ू डाल के मोर 🦚बना दूंगा 🤩🥵😱",
    "तेरी मां के चूत में थानेदार उल्डरिंग कर दूंगा हिलते हुए भी दर्द होगा😱🤮👺",
    "तेरी मां को रेडी पे बैठल के उसकी उसकी चूत बिलवाउंगा 💰 😵🤩",
    "भोसदिके तेरी मां की चूत में 4 होले है उनमे मसील लगा बहुत लगती है भोफडीके 👊🤮🤢🤢 ",
    "तेरी बहन की चूत में बरगद का पेड़ उगा दूंगा कोरोना में सब ऑक्सीजन लेकर जाएंगे🤢🤩🥳",
    "तेरी मां की चूत में सूडो लगा के बिगस्पम लगा के 9999 चोद लगा दू 🤩🥳🔥",
    "तेरी बहन के भो ओएसडाइक मैं बेसन के लड्डू भर दूंगा🤩🥳🔥😈",
    "तेरी मां की चूत खोद के उसे सिलेंडर ⛽️ फिट करके हमें दाल मखनी बनाऊंगा🤩👊🔥",
    "तेरी मां की चूत में शीशा दाल दूंगा और चौराहे पे तांग डूंगा भोसडाइक😈😱 🤩",
    "तेरी मां की चूत में क्रेडिट कार्ड डाल के उम्र से 500 साल पहले नोट निकालूंगा भोसड़ाके💰💰🤩",
    "तेरी मां के साथ सुर का सेक्स करवा दूंगा एक साथ 6-6 बच्चे देगी💰🔥😱",
    " तेरी बहन की चूत में एप्पल का 18W वाला चार्जर 🔥🤩",
    "तेरी बहन की गांड में वनप्लस का रैप चार्जर 30W हाई पावर 💥😂😎",
    "तेरी बहन की चूत को अमेज़न से ऑर्डर करुंगा 10 रुपये में और फ्लिप एआरटी पीई 20 रुपये मेई बेक डुंगा 🤮👿😈🤖 वीओ एक या फ्री डिलीवरी देगी🙀👍🥳🔥",
    "तेरी बहन की चूत काली🙁🤣💥",
    "तेरी मां की चूत में बदलाव के लिए प्रतिबद्ध हूं, तेरी बहन की चूत अपने आप अपडेट हो जाएगी🤖🙏🤔",
    "तेरी मौसी के भोसडे मेई इंडियन रेलवे 🚂💥😂",
    "तू तेरी बहन तेरा खानदान सब बहन के लौड़े रंडी है रंडी 🤢✅🔥",
    "तेरी बहन की चूत में आयनिक बॉन्ड बना के वर्जिनिटी लूज करवा दूंगा उसकी 📚 😎🤩",
    "टेर मैं रंडी माँ से पूछना बाप का नाम बहनों के लोदी 🤩🥳😳",
    "तू और तेरी मां दोनों की भोसड़े में मेट्रो चलवा दूंगा मादरचोद 🚇🤩😱🥶",
    "तेरी मां को इतना चोदूंगा तेरा बाप भी उसको पहचानने से मना कर देगा 😂👿🤩 ",
    "तेरी बहन के भोसड़े में हेयर ड्रायर चला दूंगा💥🔥🔥",
    "तेरी मां की चूत में टेलीग्राम की सारी रंडियों का रंडी खाना खोल दूंगा👿🤮😎",
    "तेरी मां की चूत एलेक्सा डाल की डीजे बजाऊंगा 🎶 ⬆️🤩 💥",
    "तेरी माँ के भोसड़े में गिठब डाल के अपना बोट होस्ट करुंगा 🤩👊👤😍",
    "तेरी बहन का वीपीएस बना के 24*7 बैश चुदाई कमांड दे दूंगा 🤩💥🔥🔥",
    "तेरी माँ की चूत में तेरे लंड को डाल के काट दूंगा मादरचोद 🔪😂🔥",
    "सुन तेरी मां का भोसड़ा और तेरी बहन का भी भोसड़ा 👿😎👊",
    "तुझे देख के तेरी रंडी बहन पे तरस आता है मुझे बहन के लौड़े 👿 💥🤩🔥",
    "सुन मादरचोद ज्यादा न उछल मां चोद देंगे एक मिनट में ✅🤣🔥🤩",
    "अपनी अम्मा से पूछना उसको हमें काली रात में कौन चोदने आया था!",
    "तेरी वहीं नहीं है क्या? 9 महीने रुक ꜱअगी वहीं देता हूं 🤣🤣🤩", 
    "तेरी मां के भोꜱदे में एयरोप्लेनपार्क करके उड़ान भर दूंगा ✈️🛫",
    "तेरी मां की चूत में ꜱउटली बम फोड दूंगा तेरी मां की झाटे जल के खाक हो जाएगी💣",
    "तेरी माँ की चूत में ꜱकूटर डाल दूँगा👅",
    "तेरी माँ की चूत 🤱गली के कुत्ते 🦮मैं बात दूँगा फिर 🍞रोटी की तरह खाएँगे वो तेरी माँ की चूत",
    "दूध हिलाऊँगा तेरी वहीं के यूपीआर आला 🆙🆒😙",
    "तेरी माँ की चूत में ✋हत्थ डालके 👶बच्चे निकाल दूंगा 😍",
    "तेरी बहन की चूत में काले के छिलके 🍌🍌😍",
    "तेरी बहन की चूत में उꜱएरबोट लगाऊंगा ꜱaꜱते ꜱपम के चोदे" ,
    "तेरी वहीं धंधे वाली 😋😛", 
    "तेरी मां के भोकडे में एसी लगा दूंगा ꜱरी गर्मी निकल जाएगी",
    "तेरी वहीं को हॉर्लिकꜱ पीलूंगा मादरचोद😚", 
    "तेरी मां की गांड में ꜱअरिया डाल दूंगा मादरचोद uꜱi ꜱariye pr तांग के बच्चे पैदा होंगे 😱😱",
    "तेरी मां को कोलकाता वाले जीतू भैया का लंड मुबारक 🤩🤩",
    "तेरी मम्मी की फैन्टसी हूं बेटे, तू अपनी बहन को ꜱप्रभाल 😈😈",
    "तेरा पहला बाप हूं मादरचोद",
    "तेरी वहीं ke bhoꜱde me xvideoꜱ.com चला के मुंह मारूंगा 🤡😹",
    "तेरी मां का ग्रुप वालों ꜱसाथ मिलके गैंग बैंग करूंगा🙌🏻☠️",
    "तेरी आइटम की गांड में लंड डालके,तेरे जयꜱएक या निकल दूंगा मादरचोद🤘🏻🙌 🏻 ☠️ ",
    "औकात में रह वर्ना गांड में डंडा डाल के मुंह ꜱए निकाल दूंगा 🙄🤭🤭",
    "तेरी मम्मी के ꜱआठ लूडो खेलते खेलते उके मुंह में अपना लोडा दे दूंगा☝🏻☝ 🏻😬",
    " तेरी वहीं को अपने लंड पर इतना झूलाऊंगा कि झूलते-झुलते ही बच्चा पैदा कर दूंगा। छुट रुक जाएगीइइइइ🔥😍",
    "तेरी माँ के गांड में झाड़ू दाल के मोर 🦚बना दूंगा 🤩🥵😱",
    "तेरी माँ के चूत में ꜱहोल्डरिंग कर दूंगा हिलते हुए भी दर्द होगा😱🤮👺",
    "तेरी माँ को रेडी पे बैठल के उꜱꜱe उꜱकी चूत बिलवाउंगा 💰 😵🤩",
    "भोꜱदिके तेरी मां की चूत में 4 छेद हैं उनमें मेरा असली लगा बहुत बहती है भोफडाइक👊🤮🤢🤢",
    "तेरी बहन की चूत में बरगद का पेड़ उगा दूंगा एक कोरोना मेई ꜱab ऑक्सीजन Lekar Jayenge🤢🤩🥳 ",
    " तेरी माँ की चुत  खोद के तुम्हें सिलिंडर ⛽️ फिट करके उन्हें मैं दाल मखनी बनाऊंगा🤩👊🔥",
    "तेरी मां की छुट्टी में मैं क्रेडिट कार्ड डाल दूंगा और चौराहे पर टांग दूंगा",
    "तेरी मां की छुट्टी में क्रेडिट कार्ड डाल के उम्र 500 के करे कारे नोट निकालूंगा भोꜱडाइक💰💰🤩",
    "तेरी माँ के ꜱath ꜱuar का ꜱex करवा दूंगा एक ꜱath 6-6 बच्चे देगी💰🔥😱",
    "तेरी बहन की चूत में एप्पल का 18W वाला चार्जर 🔥🤩",
    "तेरी बहन की गांड में वनप्लस का रैप चार्जर 30w हाई पावर 💥😂😎",
    "तेरी बहन की बेटी को अमेज़न से ऑर्डर करूंगा 10 रुपये में और फ्लिपकार्ट पे 20 रुपये में बेच दूंगा🤮👿😈🤖",
    "तेरी माँ की बड़ी भुंड में जोमैटो दाल के ꜱubway का bff सब्जी ꜱub कॉम्बो [15 सेमी, 16 इंच ] ऑर्डर कॉड क्रवाउंगा या तेरी मां जब डिलीवरी देने आएगी तब uꜱपे जादू करूंगा या फिर 9 महीने बाद वो एक या फ्री डिलीवरी देगी🙀👍🥳🔥",
    "तेरी भेन की चुउत काली🙁🤣💥",
    "तेरी माँ की चूत में बदलावꜱकमिट करें फिर तेरी बहन की चूत स्वचालित रूप से अपडेट हो जाएगी🤖🙏🤔",
    "तेरी मौसी के भोꜱदे में भारतीय रेलवे 🚂💥😂",
    "तू तेरी बहन तेरा खानदान ꜱअब बहन के Lawde rændi hai rændi 🤢✅🔥 ",
    " teri bahen ki chuut mei ionic बॉन्ड बाना ke vor koir kirva karwa karwa dunga uꜱki 📚 📚 📚 📚 📚 📚 माँ दोनो की भोकडे में मेट्रो चलवा दूँगा मादरचोद 🚇🤩😱🥶",
    "तेरी माँ को इतना चोदूँगा तेरा बाप भी उनको पहचानने के लिए मना कर देगा😂👿🤩","तेरी बहन के भोकडे में हेयर ड्रायर चला दूँगा💥🔥 🔥", 
    "तेरी माँ की चूत में टेलीग्राम की ꜱअरी रंडियों का रंडी खाना खोल दूँगा👿🤮😎", "तेरी माँ की चूत एलेक्सा डाल के डीजे बजाऊँगा 🎶 ⬆️🤩💥", 
    "तेरी माँ के भोꜱदे में गीथूब डाल के अपना बोट होꜱ गा 🤩 👊👤😍",
    "तेरी बहन का vpꜱ बना के 24*7 baꜱh चुदाई कमांड दे दूंगा 🤩💥🔥🔥",
    "तेरी मम्मी की चूत में तेरे लंड को डाल के काट दूंगा मादरचोद 🔪😂🔥",
    "ꜱउं तेरी माँ का भोनदा और तेरी बहन का भी भोनदा 👿😎👊",
    "तुझे देख के तेरी रंडी बहन पे ताराꜱ आता है मुझे बहन के लोडी 👿💥🤩🔥",
    "तुम्हें मादरचोद ज्यादा ना उछाल माँ चोद देंगे एक मिनट में ✅ 🤣🔥🤩" ,
    "अपनी अम्मा ने पूछा तुम्हें काली रात में कौन चोदने आया था! तेरे मैं पापा का नाम लेगी। नी माँ ꜱए पुछ रंडी के बची 🤩👊👤😍",
    "तेरी मां के भोꜱदे में ꜱपोटिफाई दाल के लोफी बजाऊंगा दिन भर 😍🎶🎶💥",
    "तेरी मां का नया रंडी खाना खोलूंगा चिंता मत कर 👊🤣🤣 😳",
    "तेरा बाप hu bhoꜱदिके तेरी माँ को रंडी खाने पे चुडवा के उꜱ पैग की दारू पीता हू 🍷🤩🔥",
    "तेरी बहन की चूत में अपना बड़ा ꜱa लौड़ा घुꜱꜱa डूंगा कल्लाप के मर जाएगी 🤩😳😳🔥",
}

var ERAID = []string{
	"Motherfucker, I'll chew gutka in your mom's pussy and spit it out 🤣🤣",
	"I'll stab your mom's cunt with a knife and drain the blood 🥵",
	"I'll shove a dagger in your sister's pussy and tear it apart 😈",
	"I'll park an airplane in your mom's cunt and take off ✈️🛫",
	"I'll explode a sutli bomb in your mom's pussy, her pubes will burn to ashes 💣",
	"I'll shove a scooter inside your mom's cunt 👅",
	"I'll feed your mom's pussy to street dogs, then they'll eat it like bread 🦮🍞",
	"I'll shake and milk your sister's tits up and down 🆙😙",
	"I'll ram my dick in your sister's cunt and get her pregnant 🍌😍",
	"Your sister-in-law is a roadside whore 😋😛",
	"I'll install AC in your mom's pussy so all the heat goes away ❄️",
	"I'll make your sister-in-law drink Horlicks, you motherfucker 😚",
	"Congratulations, your mom got fucked by Kolkata's Jeetu Bhaiya's dick 🤩",
	"I'm your mom's fantasy, you limp dick. Go take care of your sister 😈",
	"I'm your first father, you motherfucker",
	"I'll play xvideos.com inside your sister-in-law's cunt and jerk off 🤡😹",
	"I'll do a gangbang with your mom along with the whole group 🙌🏻☠️",
	"I'll fuck your girl so hard in her ass, another copy of you will come out 😆",
	"Stay in your limits or I'll shove a stick up your ass and pull it out from your mouth 🙄🤭",
	"While playing Ludo with your mom, I'll put my dick in her mouth ☝🏻😬",
	"I'll ride your sister-in-law on my dick so hard she'll give birth while bouncing 💦",
	"I'll put a battery in your mom's cunt and turn her into a powerbank 🔋🔥",
	"I'll apply C++ string encryption on your mom's pussy, it'll become so tight 😈",
	"I'll shove a broom in your mom's ass and turn her into a peacock 🦚",
	"I'll do shoulder-deep fisting in your cunt, it'll hurt even while moving 😱",
	"I'll put your mom on the road and get her cunt auctioned for money 💰😵",
	"Your mom's pussy has 4 holes, I'll stuff masala in all of them, it's too loose 👊🤮",
	"I'll plant a banyan tree in your sister's cunt, people will come for oxygen during corona 🤢🤩",
	"I'll run sudo on your mom's cunt, spam big, and fuck 9999 times 🤩🔥",
	"I'll stuff besan laddoos in your sister-in-law's pussy 🤩🥳",
	"I'll dig your mom's cunt, fit a cylinder and make dal makhani 🤩👊",
	"I'll put a mirror in your mom's cunt and hang it at the chowk, you whore 😈😱",
	"I'll insert a credit card in your mom's pussy and pull out 500 black notes 💰🤩",
	"I'll make your mom fuck a pig, she'll give birth to 6-6 kids at once 💰🔥😱",
	"18W Apple charger in your sister's cunt 🔥🤩",
	"30W OnePlus Warp charger in your sister's ass 💥😂😎",
}

var PORNTEXT = []string{
	"TERI MAA KI CHUT ME MERA 12 INCH KA LODA THOK DUNGA MADARCHOD 💦😈",
	"TERI BEHEN KI GAAND ME CREAMPIE KARKE PREGNANT KAR DUNGA 🤰🍆",
	"TERI MUMMY KO DOGGY STYLE ME CHOD KE USKI CHUT FAAD DUNGA 🐶💦",
	"TERI VAHEEN KE MUH ME MUTH MAAR KE SAARA SEMEN PILA DUNGA 😋🥛",
	"TERI MAA KI CHUT ITNI WIDE HAI KI BUS DAAL SAKDA HU 🔥🚌",
	"TERI BEHEN KO RAILWAY STATION PE CHODUNGA SAB DEKH KE 😈👀",
	"TERI GF KI CHUT ME FINGERING KARTE HUE VIDEO BANAKE VIRAL KAR DUNGA 📹",
	"MADARCHOD TERI MAA KO BLUE FILM ME CAST KAR DUNGA 🍑🎬",
	"TERI BEHEN KE BOOBS DABAKE DUDH NIKAL DUNGA 🍼🤤",
	"TERI MUMMY KI GAAND ME FULL OIL LAGA KE HARD ANAL 💦🍑",
	"TERI RANDI MAA KO 5 SAAL TAK ROZ CHODUNGA NON-STOP 😩🔥",
	"TERI BEHEN KI CHUT ME MERA LUND DAAL KE 9 MONTH BAAD BETA DEGI 🤰",
	"TERI MAA KI CHUT ME APNA MOTA LUND GHUSSA KE FAAD DUNGA 🍆💥",
	"TERI BEHEN KO PUBLIC ME CHODUNGA SABKO DIKHATE HUE 😈👅",
}

var PORNVIDEOS = []string{
    "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
    "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
    "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
    "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
    "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
    "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
    "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
    "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
    "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
    "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
    "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
    "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
    "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
    "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
    "https://telegra.ph/file/50637aa9c04d136687523.mp4",
    "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
    "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
    "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
    "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
    "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
    "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
    "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
    "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
    "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
    "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
    "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
    "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
    "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
    "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
    "https://telegra.ph/file/f483400ff141de73767ca.jpg",
    "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
    "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
    "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
    "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
    "https://telegra.ph/file/b434999287d3580250960.jpg",
    "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
    "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
    "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
    "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
    "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
    "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
    "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
    "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
    "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
    "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
    "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
    "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
    "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
    "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
    "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
    "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
    "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
    "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
    "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
    "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
    "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
    "https://te.legra.ph/file/a66008b78909b431fc92b.mp4",
    "https://te.legra.ph/file/0ab82f535e1193d09c0e4.mp4",
    "https://te.legra.ph/file/1ab9cde9388117db9d26c.mp4",
    "https://te.legra.ph/file/75e49339469dbf9ad1dd2.mp4",
    "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
    "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
    "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
    "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
    "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
    "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
    "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
    "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
    "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
    "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
    "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
    "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
    "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
    "https://telegra.ph/file/50637aa9c04d136687523.mp4",
    "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
    "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
    "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
    "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
    "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
    "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
    "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
    "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
    "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
    "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
    "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
    "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
    "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
    "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
    "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
    "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
    "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
    "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
    "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
    "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
    "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
    "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
    "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
    "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
    "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
    "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
    "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
    "https://telegra.ph/file/50637aa9c04d136687523.mp4",
    "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
    "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
    "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
    "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
    "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
    "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
    "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
    "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
    "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
    "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
    "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
    "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
    "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
    "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
    "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
    "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
    "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
    "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
    "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
    "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
    "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
    "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
    "https://telegra.ph/file/f483400ff141de73767ca.jpg",
    "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
    "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
    "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
    "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
    "https://telegra.ph/file/b434999287d3580250960.jpg",
    "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
    "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
    "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
    "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
    "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
    "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
    "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
    "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
    "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
    "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
    "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
    "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
    "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
    "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
    "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
    "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
    "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
    "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
    "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
    "https://telegra.ph/file/2fcccbc72c57b6892d23a.jpg",
    "https://telegra.ph/file/843109296a90b8a6c5f68.jpg",
    "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
    "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
    "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
    "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
    "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
    "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
    "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
    "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
    "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
    "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
    "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
    "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
    "https://telegra.ph/file/50637aa9c04d136687523.mp4",
    "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
    "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
    "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
    "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
    "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
    "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
    "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
    "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
    "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
    "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
    "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
    "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
    "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
    "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
    "https://telegra.ph/file/f483400ff141de73767ca.jpg",
    "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
    "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
    "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
    "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
    "https://telegra.ph/file/b434999287d3580250960.jpg",
    "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
    "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
    "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
    "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
    "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
    "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
    "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
    "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
    "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
    "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
    "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
    "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
    "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
    "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
    "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
    "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
    "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
    "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
    "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
}
